# .github/workflows/deploy.yml

name: Deploy Streamlit App

on:
  workflow_run:
    workflows: ["Test Streamlit App"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Sync code to EC2
        run: |
          rsync -az --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Recreate venv and install dependencies (on EC2)
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/app &&
            python3 -m venv venv &&
            source venv/bin/activate &&
            poetry install --no-interaction
          "

      - name: Restart systemd Streamlit service
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "
            sudo systemctl daemon-reload &&
            sudo systemctl restart streamlit-tempocom.service &&
            sudo systemctl status streamlit-tempocom.service --no-pager
          "
